"""Hodge Conjecture — toy investigation of Hodge diamonds (stdlib only).

The conjecture: on a smooth complex projective variety, every "Hodge class"
(a rational cohomology class of type (p,p)) is a rational linear combination
of classes of algebraic subvarieties.

We can't test that in general, but we CAN build the Hodge diamonds
h^{p,q} = dim H^{p,q} for textbook varieties and enumerate the Hodge
classes the conjecture talks about. For CP^2 there is exactly one per
even degree, all known to be algebraic (generated by a line) — consistent
with the conjecture.

Run: python3 investigate.py
"""


def hodge_cp(n):
    """Hodge numbers of complex projective space CP^n: h^{p,q} = 1 iff p==q<=n."""
    return {(p, q): 1 if p == q <= n else 0 for p in range(n + 1) for q in range(n + 1)}


def hodge_elliptic_curve():
    return {(0, 0): 1, (1, 0): 1, (0, 1): 1, (1, 1): 1}


def hodge_k3():
    h = {(p, q): 0 for p in range(3) for q in range(3)}
    h.update({(0, 0): 1, (2, 2): 1, (2, 0): 1, (0, 2): 1})
    h[(1, 1)] = 20
    return h


def hodge_classes(h, p):
    """Dimension of H^{2p} cap H^{p,p}, i.e. number of Hodge classes in degree 2p."""
    return h.get((p, p), 0)


def print_diamond(h, n, name):
    print(f"\n{name} Hodge diamond:")
    for p in range(n + 1):
        row = " ".join(str(h.get((p, q), 0)) for q in range(n + 1))
        print(f"  p={p}: {row}")


def self_test():
    assert hodge_classes(hodge_cp(2), 0) == 1
    assert hodge_classes(hodge_cp(2), 1) == 1  # generated by a line -> algebraic
    assert hodge_classes(hodge_cp(2), 2) == 1
    assert hodge_classes(hodge_elliptic_curve(), 1) == 1
    assert hodge_classes(hodge_k3(), 1) == 20  # K3: 20-dim space of (1,1)-classes
    print("self-test OK")


if __name__ == "__main__":
    self_test()
    print_diamond(hodge_cp(2), 2, "CP^2")
    print("\nCP^2 Hodge classes per degree 2p:", {p: hodge_classes(hodge_cp(2), p) for p in (0, 1, 2)})
    print("All are multiples of [line]^p -> algebraic. Consistent with Hodge.")
    print_diamond(hodge_k3(), 2, "K3 surface")
    print("\nK3 has a 20-dim space of (1,1)-classes; Hodge predicts all are")
    print("algebraic. This is known for K3, open in general.")
